---

- name: Import role
  theforeman.foreman.job_template:
    name: SAPO - Remove Files
    provider_type: Ansible
    job_category: SAPO - Ansible
    state: present
    validate_certs: no
    template: | 
      <%#

      ---

      - name: PLAYBOOK REMOVE FILES
        hosts: all
        become: true
        tasks:

        - name: REMOVE FILES
          block:

            - name: REMOVE FILES | Create folder
              ansible.builtin.file:
                path: "{{ folder }}"
                state: directory
                mode: '0755'

            - name: REMOVE FILES | Create files
              ansible.builtin.file: 
                path: /tmp/files/"{{ files }}"
                state: touch
                mode: 0775

            - name: REMOVE FILES | Create old files
              ansible.builtin.file: 
                path: /tmp/files/"{{ old_files }}"
                state: touch
                mode: 0775
                modification_time: "202107081234.56"

            - name: REMOVE FILES | Remove old files
              ansible.builtin.shell: "find /tmp/files/* -mtime +30 -exec rm -rfv '{}' +"
              register: filesremoved
      
            - name: REMOVE FILES | Show Files Removed
              debug:
                msg: "{{ filesremoved.stdout_lines }}"

          always:

            - name: LOGBOOK REMOVE FILES
              lineinfile:
                path: /var/log/exec_ansible.log
                line: "{{ lookup('pipe','TZ=\"Europe/Lisbon\" date +%d/%m/%Y-%H:%M:%S') }} - Exec PLAYBOOK REMOVE FILES"
                create: yes

      ...

      %>

    locations:
    - Default Location
    organizations:
    - Default Organization

...