---

- name: UBUNTU INSTALL PACKAGE
  block:

    - name: UBUNTU | Apt Update
      ansible.builtin.shell: "apt update"

    - name: UBUNTU | Install package {{ package }}
      ansible.builtin.apt:
        name: "{{ package }}"
        state: latest

    - name: UBUNTU | Check version installed
      ansible.builtin.shell: "apt list --installed | grep {{ package }}"
      register: packageversion

    - name: UBUNTU | Show {{ package }} Version
      debug:
        msg: "{{ package }} Version is {{ packageversion.stdout }}"

  when:
    - ansible_facts['distribution'] is defined and ansible_facts['distribution'] == 'Ubuntu'

- name: CENTOS INSTALL PACKAGE
  block:

    - name: CENTOS | Install package {{ package }}
      ansible.builtin.yum:
        name: "{{ package }}"
        state: latest

    - name: CENTOS | Check version installed
      ansible.builtin.shell: "rpm -qa {{ package }}"
      register: packageversion

    - name: CENTOS | Show {{ package }} Version
      debug:
        msg: "{{ package }} Version is {{ packageversion.stdout }}"

  when:
    - ansible_facts['distribution'] is defined and ansible_facts['distribution'] == 'CentOS'

...