---
- name: "{{ L0000_descricao }}"

# -------------------------------------------------------------
  block:
# -------------------------------------------------------------

- name: L0000(1) - IHSCONF CHECA ARQUIVOS
  ignore_errors: yes
  shell: "{{ item }}"
  with_items:
    - find /opt/IHSCONF/{{ hostname | lower }}/logs/{{ hostname | lower }}/ -type f \( -name \*.log -o -name \*.gz \) -mtime +3 -print 2>/dev/null | wc -l
  register: limpezaihs1

- name: L0000(2) - IHSCONF REMOVE ARQUIVOS
  ignore_errors: yes
  shell: "{{ item }}"
  with_items:
    - find /opt/IHSCONF/{{ hostname | lower }}/logs/{{ hostname | lower }}/ -type f \( -name \*.log -o -name \*.gz \) -mtime +3 -exec rm -f {} \;
  when: limpezaihs1.results[0].stdout != "0"

- name: L0000(3) - IHSCONF CHECA ARQUIVOS
  ignore_errors: yes
  shell: "{{ item }}"
  with_items:
    - find /opt/IHSCONF/{{ hostname | upper }}/logs/{{ hostname | upper }}/ -type f \( -name \*.log -o -name \*.gz \) -mtime +3 -print 2>/dev/null | wc -l
  register: limpezaihs2

- name: L0000(4) - IHSCONF REMOVE ARQUIVOS
  ignore_errors: yes
  shell: "{{ item }}"
  with_items:
    - find /opt/IHSCONF/{{ hostname | upper }}/logs/{{ hostname | upper }}/ -type f \( -name \*.log -o -name \*.gz \) -mtime +3 -exec rm -f {} \;
  when: limpezaihs2.results[0].stdout != "0"

# -------------------------------------------------------------
  rescue:
# -------------------------------------------------------------

    - set_fact:
        add_info: 'Falha na limpeza L0000'
    - debug:
        msg: "{{ add_info }}"
    - fail: